### ISSUE TITLE
Add Elizabethtown College, PA, USA

### ISSUE THREAD

**Issue by Peilong** [ryanswanstrom/awesome-datascience-colleges#67]
Please add Elizabethtown College's B.S. degree in Data Science to the list. Please find the information as follows.

Elizabethtown College | Data Science | B | F | T | US | PA | Elizabethtown | Computer Science | https://www.etown.edu/depts/computer-science/data-science-major.aspx

Thanks

**Comment by ryanswanstrom** [comment]
Thank you @Peilong 
Elizabethtown is now added
https://ryanswanstrom.com/colleges/
